Repository BlueBrain/nexus-web, pull requests merged in 2019-01, with the labels that each got.

#82 Add edit project
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/Breadcrumb/getBreadcrumbs.tsx.html
  coverage/lcov-report/Breadcrumb/index.html
  coverage/lcov-report/Header/index.html
  coverage/lcov-report/Header/index.tsx.html
  coverage/lcov-report/Login/index.html
  coverage/lcov-report/Login/index.tsx.html
  coverage/lcov-report/Projects/ProjectForm.tsx.html
  coverage/lcov-report/Projects/index.html
  coverage/lcov-report/base.css
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  package-lock.json
  package.json
  src/shared/components/Breadcrumb/__tests__/Breadcrumb.test.tsx
  src/shared/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
  src/shared/components/Header/__tests__/Header.test.tsx
  src/shared/components/Header/__tests__/__snapshots__/Header.test.tsx.snap
  src/shared/components/Login/__tests__/Login.test.tsx
  src/shared/components/Login/__tests__/__snapshots__/Login.test.tsx.snap
  src/shared/components/Projects/ProjectForm.tsx
  src/shared/components/Projects/ProjectList.tsx
  src/shared/components/Projects/Projects.stories.tsx
  src/shared/components/Projects/__tests__/ProjectForm.spec.tsx
  src/shared/components/Projects/__tests__/__snapshots__/ProjectForm.spec.tsx.snap
  src/shared/components/Resources/Resources.stories.tsx
  src/shared/store/actions/nexus.ts
  src/shared/store/actions/project.ts
  src/shared/views/Home.tsx
Labels: review

#84 fix display resources
  package-lock.json
  package.json
Labels: review

#85 Create projects
  package-lock.json
  package.json
  src/shared/store/actions/project.ts
  src/shared/views/Home.tsx
  src/shared/views/Landing.tsx
Labels: review

#86 remove folder. Commited by mistake
  .gitignore
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/Breadcrumb/getBreadcrumbs.tsx.html
  coverage/lcov-report/Breadcrumb/index.html
  coverage/lcov-report/Header/index.html
  coverage/lcov-report/Header/index.tsx.html
  coverage/lcov-report/Login/index.html
  coverage/lcov-report/Login/index.tsx.html
  coverage/lcov-report/Projects/ProjectForm.tsx.html
  coverage/lcov-report/Projects/index.html
  coverage/lcov-report/base.css
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
Labels: review

#87 Use latest sdk
  package-lock.json
  package.json
  src/shared/views/Home.tsx
Labels: review

#81 SPARQL and ElasticSearch view query UI
  package-lock.json
  package.json
  src/shared/components/Projects/Projects.less
  src/shared/components/RawQueryView/RawElasticSearchQueryView.tsx
  src/shared/components/RawQueryView/RawSparqlQueryView.tsx
  src/shared/routes.tsx
  src/shared/store/actions/nexus.ts
  src/shared/store/actions/rawQuery.ts
  src/shared/store/index.ts
  src/shared/store/reducers/index.ts
  src/shared/store/reducers/nexus.ts
  src/shared/store/reducers/rawQuery.ts
  src/shared/views/RawQuery.tsx
  src/shared/views/breadcrumbs/BreadcrumbLabels.tsx
Labels: nexus-web, review

#88 alpha-1
  package-lock.json
  package.json
Labels: review

#89 Bugfix/label input and refresh on path change
  src/shared/components/Projects/ProjectForm.tsx
  src/shared/views/Home.tsx
Labels: review

#90 Org form
  src/shared/components/Orgs/OrgCard.tsx
  src/shared/components/Orgs/OrgForm.tsx
  src/shared/components/Orgs/OrgList.tsx
  src/shared/components/Orgs/Orgs.stories.tsx
  src/shared/components/Orgs/__tests__/OrgForm.spec.tsx
  src/shared/components/Orgs/__tests__/__snapshots__/OrgForm.spec.tsx.snap
  src/shared/components/Projects/ProjectForm.tsx
  src/shared/store/actions/orgs.ts
  src/shared/views/Landing.tsx
Labels: review

#91 Fixing pagination for ElasticSearchView
  src/shared/components/RawQueryView/RawElasticSearchQueryView.tsx
  src/shared/components/Resources/ResourceList.tsx
  src/shared/store/actions/rawQuery.ts
  src/shared/store/reducers/rawQuery.ts
Labels: nexus-web, review

#83 Editable, Filterable Lists
  package-lock.json
  package.json
  src/client/index.tsx
  src/shared/App.less
  src/shared/App.tsx
  src/shared/components/Animations/FlipCard.less
  src/shared/components/Animations/FlipCard.tsx
  src/shared/components/Header/__tests__/__snapshots__/Header.test.tsx.snap
  src/shared/components/Lists/FilterDropdown.less
  src/shared/components/Lists/FilterDropdown.tsx
  src/shared/components/Lists/ListControlPanel.tsx
  src/shared/components/Lists/ListItem.tsx
  src/shared/components/Lists/Lists.less
  src/shared/components/Lists/index.tsx
  src/shared/components/Login/__tests__/__snapshots__/Login.test.tsx.snap
  src/shared/components/Renameable/Renameable.less
  src/shared/components/Renameable/Renameable.stories.tsx
  src/shared/components/Renameable/index.tsx
  src/shared/components/Resources/ResourceList.tsx
  src/shared/components/Resources/ResourceListContainer.tsx
  src/shared/components/Resources/Resources.less
  src/shared/layouts/MainLayout.less
  src/shared/layouts/MainLayout.tsx
  src/shared/lib.less
  src/shared/routes.tsx
  src/shared/store/actions/lists.ts
  src/shared/store/actions/nexus/index.ts
  src/shared/store/actions/nexus/projects.ts
  src/shared/store/actions/queryResource.ts
  src/shared/store/actions/utils/index.ts
  src/shared/store/index.ts
  src/shared/store/reducers/index.ts
  src/shared/store/reducers/lists.ts
  src/shared/store/reducers/localStorage.ts
  src/shared/store/reducers/nexus/index.ts
  src/shared/store/reducers/nexus/project.ts
  src/shared/store/reducers/utils/createByKey.test.ts
  src/shared/store/reducers/utils/createByKey.ts
  src/shared/store/reducers/utils/index.ts
  src/shared/styles/close-button.less
  src/shared/utils/index.ts
  src/shared/views/Project.tsx
  src/shared/views/RawQuery.tsx
  src/shared/views/breadcrumbs/BreadcrumbLabels.tsx
Labels: enhancement, review

#92 refactoring nexus reducer
  src/shared/components/Orgs/__tests__/__snapshots__/OrgForm.spec.tsx.snap
  src/shared/components/Projects/__tests__/__snapshots__/ProjectForm.spec.tsx.snap
  src/shared/routes.tsx
  src/shared/store/actions/lists.ts
  src/shared/store/actions/nexus/activeOrg.ts
  src/shared/store/actions/nexus/index.ts
  src/shared/store/actions/nexus/orgs.ts
  src/shared/store/actions/nexus/projects.ts
  src/shared/store/actions/queryResource.ts
  src/shared/store/actions/utils/index.ts
  src/shared/store/reducers/nexus.ts
  src/shared/store/reducers/nexus/index.ts
  src/shared/store/reducers/nexus/project.ts
  src/shared/store/reducers/utils/createByKey.test.ts
  src/shared/store/reducers/utils/index.ts
  src/shared/views/Home.tsx
  src/shared/views/Landing.tsx
  src/shared/views/Project.tsx
  src/shared/views/RawQuery.tsx
  src/shared/views/breadcrumbs/BreadcrumbLabels.tsx
Labels: enhancement, review

#95 fixed
  package-lock.json
  src/shared/store/reducers/localStorage.ts
Labels: review

#96 remove extra class and overwrite for full width instead
  src/shared/components/Lists/ListItem.tsx
  src/shared/components/Lists/index.tsx
  src/shared/layouts/MainLayout.less
  src/shared/layouts/MainLayout.tsx
  src/shared/views/Project.tsx
Labels: review

#98 🚧 WIP: add simple resource creation form
  package-lock.json
  package.json
  src/shared/components/FileUpload/index.tsx
  src/shared/components/Lists/FilterDropdown.less
  src/shared/components/Lists/FilterDropdown.tsx
  src/shared/components/Lists/index.tsx
  src/shared/components/Resources/ResourceForm.tsx
  src/shared/store/actions/nexus/projects.ts
  src/shared/views/Project.tsx
Labels: review

#101 Copy Token
  src/shared/components/Copy/Copy.stories.tsx
  src/shared/components/Copy/index.tsx
  src/shared/components/Header/Header.less
  src/shared/components/Header/index.tsx
  src/shared/layouts/MainLayout.tsx
Labels: review

#99 Make project public
  package-lock.json
  package.json
  src/shared/components/Projects/ProjectForm.tsx
  src/shared/store/actions/project.ts
  src/shared/views/Home.tsx
Labels: review

#103 make sure we list all project and orgs
  src/shared/components/Projects/ProjectCard.tsx
  src/shared/store/actions/nexus/activeOrg.ts
  src/shared/store/actions/nexus/orgs.ts
Labels: review

#104 using latest sdk and hide uploader
  package-lock.json
  package.json
  src/shared/components/Workspace/Menu.tsx
Labels: review

#106 Fix view name
  package-lock.json
  package.json
  src/shared/components/Workspace/Menu.tsx
  src/shared/store/reducers/lists.ts
Labels: review

#108 Better button label
  src/shared/views/Landing.tsx
Labels: nexus-web, review

#109 323 hover resources
  package-lock.json
  package.json
  src/shared/App.less
  src/shared/components/Resources/ResourceItem.tsx
Labels: review
