Repository BlueBrain/nexus-web, pull requests merged in 2024-01, with the labels that each got.

#1453 HOTFIX: Fix Jest snapshot
  src/shared/components/JIRA/__tests__/__snapshots__/JIRA.spec.tsx.snap
Labels: fix

#1456 Favicon in prod
  index.html
  server/index.ts
  vite.config.js
Labels: fix

#1455 HOTFIX: Increase GitHub Action timeout for new release
  .github/workflows/review.yml
  cypress.config.ts
Labels: fix

#1448 Optimize Elasticsearch view and indexing error retrieval
  src/subapps/admin/components/Settings/ViewIndexingErrors.tsx
  src/subapps/admin/components/Settings/ViewsSubView.spec.tsx
  src/subapps/admin/components/Settings/ViewsSubView.tsx
Labels: enhancement, bug

#1467 Remove `html` folder
  html/assets/index-O8DR2YZv.js
  html/assets/index-z19Uws5U.css
  html/bg.png
  html/favicon.svg
  html/html.meta.json.gz
  html/index.html
Labels: chore

#1440 Add VS Code settings (debugger, recommended extensions etc.)
  .editorconfig
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
Labels: enhancement

#1468 Undeprecate other resource types (`schemas`, `views` and `storages`)
  src/shared/containers/ResourceViewContainer.tsx
Labels: feature

#1476 Rename copy labels
  bun.lockb
  src/shared/components/ResourceActions/index.tsx
  src/shared/containers/ResourceViewActionsContainer.tsx
Labels: enhancement

#1474 Adjust custom linter logic for code editor
  src/shared/components/ResourceEditor/customLinter.spec.ts
  src/shared/components/ResourceEditor/customLinter.ts
  src/subapps/studioLegacy/containers/AddWorkspaceContainer.tsx
Labels: fix
