Repository BlueBrain/nexus-web, pull requests merged in 2024-03, with the labels that each got.

#1514 Migration/fix Query Editor line jumping
  src/shared/components/ResourceEditor/ResourceEditor.scss
  src/subapps/admin/components/Projects/QueryEditor.tsx
  src/subapps/admin/components/ViewForm/ElasticSearchQueryForm.tsx
  src/subapps/admin/components/ViewForm/SparqlQueryInput.tsx
  src/subapps/admin/components/ViewForm/view-form.scss
  src/subapps/admin/containers/ElasticSearchQuery.tsx
Labels: fix, migration

#1512 Fix loading of resources that have encoded chars in id
  README.md
  c.env.json
  ci/config/fields.json
  cypress.config.ts
  cypress/e2e/AnalysisPlugin.cy.ts
  cypress/e2e/ResourceContainer.cy.ts
  docs/development.md
  package.json
  src/subapps/studioLegacy/containers/__tests__/WorkSpaceMenuContainer.spec.tsx
  yarn.lock
Labels: fix, migration

#1517 Fix Query the view redirect to correct view editor
  src/shared/containers/ResourceViewActionsContainer.tsx
  src/shared/hooks/useAccessDataForTable.tsx
  src/shared/molecules/MyDataTable/MyDataTable.tsx
  src/subapps/admin/components/Projects/QueryEditor.scss
  src/subapps/admin/components/Projects/QueryEditor.tsx
  src/subapps/admin/index.tsx
  src/subapps/dataExplorer/DataExplorerTable.tsx
  src/subapps/search/containers/SearchContainer.tsx
Labels: fix

#1516 Migration/chore Clean docs directory
  .github/pull_request_template.md
  README.md
  docs/assets/Blue-Brain-Nexus-Fusion-Github-banner.jpg
  docs/assets/authentication_sequence_diagram.png
  docs/authFlow.md
  docs/authentication.seqdiag
  docs/development.md
  docs/plugins.md
  docs/studio/Dashboards.md
  docs/studio/studios.md
  migrations/README.md
Labels: documentation, migration
